"""delelted enum from transaction

Revision ID: 85e3af8ff603
Revises: cc29128777c2
Create Date: 2025-03-05 11:38:12.596205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85e3af8ff603'
down_revision: Union[str, None] = 'cc29128777c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'status',
               existing_type=postgresql.ENUM('not_synchronized', 'synchronized', name='transaction_status'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('not_synchronized', 'synchronized', name='transaction_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
