"""init

Revision ID: afd008461442
Revises: 
Create Date: 2025-03-04 21:56:48.684794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd008461442'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('from_dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('to_dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'from_dttm', name='uq_customer_from')
    )
    op.create_index('idx_customer_from', 'balance_history', ['customer_id', 'from_dttm'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_amt', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_index('idx_customer_from', table_name='balance_history')
    op.drop_table('balance_history')
    # ### end Alembic commands ###
