"""add statusd to transaction

Revision ID: cc29128777c2
Revises: afd008461442
Create Date: 2025-03-04 23:33:31.648533

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc29128777c2"
down_revision: Union[str, None] = "afd008461442"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE transaction_status AS ENUM('not_synchronized', 'synchronized')")
    op.add_column(
        "transactions",
        sa.Column(
            "status",
            sa.Enum("NOT_SYNCHRONIZED", "SYNCHRONIZED", name="transaction_status"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "status")
    # ### end Alembic commands ###
